version: "3"
services:
  client:
    image: "peterlubbs/multi-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "peterlubbs/multi-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "peterlubbs/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "peterlubbs/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "3050:80"
